### PR TITLE
Fixed job cancelled event

### PR DESCRIPTION
**Pull request by danielalmeida1481**
Fixed job cancelled when job was an external contract (this error ocurred because there was no penalty amount)

### CODE REVIEW

**Comment by RenCloud** [comment]
Hi,
Thanks for the commit. 

It's not much changes, but i needed a second to review that. Mostly because of the remove of the jobFinish event for C#. However, i remembered it was just a redundant event as it cannot be fired without the canceled or delivered event (or it shouldn't).

But beside that it seems fine and after i test it i will merge it 👍 .

**Comment by pat2381** [comment]
The compiled version of scs-telemetry does not work. The compilation goes without errors. ETS2 does not load the file.
Excuse me for bad english

**Comment by danielalmeida1481** [comment]
@pat2381 Remember that the default configuration of the build is 64 bits and you need to have the game in version 1.35+

**Comment by pat2381** [comment]
yes that knows. Is the windows SDK version important?
The Windows SDK version for scs-telemetry is 10.0.17134.0?
Sorry but my programming experience is not so good yet

**Comment by danielalmeida1481** [comment]
In this case it is not important since you have a recent SDK.
Where are you putting the compiled dll?

**Comment by pat2381** [comment]
i insert hier : SteamLibrary\steamapps\common\Euro Truck Simulator 2\bin\win_x64\plugins

**Comment by danielalmeida1481** [comment]
When you start the game does this message appear?
image
If it doesn't appear check if you are really running the game in 64 bits

**Comment by pat2381** [comment]
No, I did not get message.
But I think now it works. It's just very crazy. I tried to compile the file several times. But the whole time the file has a size of 71Kb. But now after compiling 20 times, the file has 43Kb and works! I just do not know what I have done now. Sorry for my mistake.

**Comment by danielalmeida1481** [comment]
Maybe you copied the wrong file.
There are 2 files, one that is a C# class and another that is the plugin.
The plugin it's compiled to the release folder and the C# class it's located in the debug folder

**Comment by RenCloud** [comment]
Please create an issue the next time and not comment a closed pull request, thanks.

**Pull request merged**
